In [1]:
# BLOCK 1

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import KFold
from tqdm import tqdm
import os
from datetime import datetime
import optuna


/home/erkkit/nnw/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# BLOCK 2

import numpy as np
import os

def load_data(directory):
    files = [f for f in os.listdir(directory) if f.endswith('.npz')]
    images_list = []
    labels_list = []

    for file in sorted(files):
        data = np.load(os.path.join(directory, file), allow_pickle=True)
        images = data['images']
        labels = data['labels']

        images_list.append(images)
        labels_list.extend(labels)

    images_combined = np.concatenate(images_list, axis=0)
    labels_combined = np.array(labels_list, dtype=np.int32)

    return images_combined, labels_combined

In [3]:
# BLOCK 3

import torch
import torch.nn as nn
import torch.nn.functional as F

class CNNModel(nn.Module):
    def __init__(self, conv1_filters=32, conv2_filters=64, conv3_filters=128, fc1_units=128, dropout_rate=0.5):
        super(CNNModel, self).__init__()
        self.conv1 = nn.Conv2d(1, conv1_filters, kernel_size=3, padding=1)  # Changed to 1 channel for grayscale
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(conv1_filters, conv2_filters, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(conv2_filters, conv3_filters, kernel_size=3, padding=1)

        self.fc1 = nn.Linear(conv3_filters * 32 * 32, fc1_units)  # Adjusted the size accordingly
        self.dropout = nn.Dropout(dropout_rate)
        self.fc2 = nn.Linear(fc1_units, 2)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(x.size(0), -1)
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)
        return x


In [4]:
# BLOCK 4

from datetime import datetime

def train_and_evaluate(X, y, fold_count=7, conv1_filters=32, conv2_filters=64, conv3_filters=128, fc1_units=128, dropout_rate=0.5):
    print(f"Training with {fold_count} folds")
    kf = KFold(n_splits=fold_count)
    results = []
    best_model = None
    best_f1 = 0.0

    for fold, (train_index, val_index) in enumerate(kf.split(X)):
        print("Starting new fold")
        X_train, X_val = X[train_index], X[val_index]
        y_train, y_val = y[train_index], y[val_index]

        print(f"Fold {fold + 1}:")
        print(f"  X_train shape: {X_train.shape}")
        print(f"  y_train shape: {y_train.shape}")
        print(f"  X_val shape: {X_val.shape}")
        print(f"  y_val shape: {y_val.shape}")

        X_train_tensor = torch.tensor(X_train, dtype=torch.float32).unsqueeze(1)
        y_train_tensor = torch.tensor(y_train, dtype=torch.long)
        X_val_tensor = torch.tensor(X_val, dtype=torch.float32).unsqueeze(1)
        y_val_tensor = torch.tensor(y_val, dtype=torch.long)

        train_loader = DataLoader(TensorDataset(X_train_tensor, y_train_tensor), batch_size=16, shuffle=True)
        val_loader = DataLoader(TensorDataset(X_val_tensor, y_val_tensor), batch_size=16, shuffle=False)

        model = CNNModel(conv1_filters, conv2_filters, conv3_filters, fc1_units, dropout_rate)
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=0.001)

        model.train()
        for epoch in tqdm(range(20), desc=f'Training fold {fold + 1}'):
            for inputs, labels in train_loader:
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()

        model.eval()
        with torch.no_grad():
            val_predictions = []
            val_true = []
            for inputs, labels in val_loader:
                outputs = model(inputs)
                _, predicted = torch.max(outputs.data, 1)
                val_predictions.extend(predicted.numpy())
                val_true.extend(labels.numpy())

        accuracy = accuracy_score(val_true, val_predictions)
        precision = precision_score(val_true, val_predictions, average='macro')
        recall = recall_score(val_true, val_predictions, average='macro')
        f1 = f1_score(val_true, val_predictions, average='macro')

        print(f"  Results for fold {fold + 1}:")
        print(f"    Accuracy: {accuracy}")
        print(f"    Precision: {precision}")
        print(f"    Recall: {recall}")
        print(f"    F1 Score: {f1}")
        results.append((accuracy, precision, recall, f1))

        if f1 > best_f1:
            best_f1 = f1
            best_model = model

    avg_results = np.mean(results, axis=0)
    print(f"Average results across all folds:")
    print(f"  Accuracy: {avg_results[0]}")
    print(f"  Precision: {avg_results[1]}")
    print(f"  Recall: {avg_results[2]}")
    print(f"  F1 Score: {avg_results[3]}")

    return best_model, results



In [5]:
# BLOCK 5

# Define global variables for the data
X_train_sample, y_train_sample = None, None

def objective(trial):
    conv1_filters = trial.suggest_int('conv1_filters', 16, 64, step=16)
    conv2_filters = trial.suggest_int('conv2_filters', 32, 128, step=32)
    conv3_filters = trial.suggest_int('conv3_filters', 64, 256, step=64)
    fc1_units = trial.suggest_int('fc1_units', 64, 256, step=64)
    dropout_rate = trial.suggest_float('dropout_rate', 0.3, 0.7, step=0.1)

    best_model, results = train_and_evaluate(X_train_sample, y_train_sample, fold_count=3, conv1_filters=conv1_filters, conv2_filters=conv2_filters, conv3_filters=conv3_filters, fc1_units=fc1_units, dropout_rate=dropout_rate)
    avg_f1 = np.mean([result[3] for result in results])
    return avg_f1

In [6]:
# BLOCK 6

# Load data directly from files
train_metrics, train_labels = load_data('./npz_results/train')
val_metrics, val_labels = load_data('./npz_results/val')
test_metrics, test_labels = load_data('./npz_results/test')

# Cap the data size to 10% for hyperparameter tuning
def sample_data(X, y, sample_fraction=0.005):
    sample_size = int(len(X) * sample_fraction)
    indices = np.random.choice(len(X), sample_size, replace=False)
    return X[indices], y[indices]

X_train_sample, y_train_sample = sample_data(train_metrics, train_labels, sample_fraction=0.005)
X_val_sample, y_val_sample = sample_data(val_metrics, val_labels, sample_fraction=0.005)
X_test_sample, y_test_sample = sample_data(test_metrics, test_labels, sample_fraction=0.005)

# Full data for final training
X_train_full, y_train_full = train_metrics, train_labels
X_val_full, y_val_full = val_metrics, val_labels
X_test_full, y_test_full = test_metrics, test_labels

print("Full data shapes:")
print(X_train_full[0], X_train_full.shape)
print(y_train_full[0], y_train_full.shape)
print(X_val_full[0], X_val_full.shape)
print(y_val_full[0], y_val_full.shape)
print(X_test_full[0], X_test_full.shape)
print(y_test_full[0], y_test_full.shape)

print("Sample data shapes:")
print(X_train_sample[0], X_train_sample.shape)
print(y_train_sample[0], y_train_sample.shape)
print(X_val_sample[0], X_val_sample.shape)
print(y_val_sample[0], y_val_sample.shape)
print(X_test_sample[0], X_test_sample.shape)
print(y_test_sample[0], y_test_sample.shape)



Full data shapes:
[[  0 255 255 ... 255 255 255]
 [255   0   0 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]] (267841, 256, 256)
0 (267841,)
[[  0 255 255 ... 255 255 255]
 [255   0 255 ... 255 255 255]
 [255 255   0 ... 255 255 255]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0 255   0]] (57394, 256, 256)
0 (57394,)
[[  0 255 255 ... 255 255 255]
 [255   0 255 ... 255 255 255]
 [255 255   0 ... 255 255 255]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ... 255   0   0]] (57395, 256, 256)
0 (57395,)
Sample data shapes:
[[  0 255 255 ... 255 255   0]
 [255   0   0 ... 255   0   0]
 [255 255 255 ...   0   0   0]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]] (1339, 256, 256)
0 (1339,)
[[  0   0 255 ... 255 255 255]
 [255 255   0 ... 255 255 255]
 [255 255 255 ..

In [7]:
def print_first_entry(directory):
    files = [f for f in os.listdir(directory) if f.endswith('.npz')]
    if files:
        data = np.load(os.path.join(directory, files[0]), allow_pickle=True)
        images = data['images']
        labels = data['labels']
        
        # Print the first entry of images and labels
        print("First entry of images:")
        print(images[0])
        print("Shape of first entry:", images[0].shape)
        
        print("\nFirst entry of labels:")
        print(labels[0])

# Call the function for one of the directories
print_first_entry('./npz_results/train')

First entry of images:
[[  0   0   0 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ...   0   0   0]
 [255 255 255 ...   0   0   0]
 [255 255 255 ... 255   0   0]]
Shape of first entry: (256, 256)

First entry of labels:
0


In [ ]:
# For pipeline testing
# train_and_evaluate(X_train_sample, y_train_sample, fold_count=3)

In [8]:
# BLOCK 7

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)

best_trial = study.best_trial
print(f"Best trial: {best_trial.values}")
print(f"Best hyperparameters: {best_trial.params}")



[I 2024-06-04 00:45:15,952] A new study created in memory with name: no-name-31267421-47b6-4618-a6a7-04340a34d402


Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [03:08<00:00,  9.43s/it]


  Results for fold 1:
    Accuracy: 0.6823266219239373
    Precision: 0.6609245071475287
    Recall: 0.645976353928299
    F1 Score: 0.6493923994697305
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [03:03<00:00,  9.17s/it]
/home/erkkit/nnw/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


  Results for fold 2:
    Accuracy: 0.6322869955156951
    Precision: 0.31614349775784756
    Recall: 0.5
    F1 Score: 0.3873626373626374
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [03:10<00:00,  9.52s/it]
/home/erkkit/nnw/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-06-04 00:54:47,637] Trial 0 finished with value: 0.47747299782397806 and parameters: {'conv1_filters': 16, 'conv2_filters': 32, 'conv3_filters': 128, 'fc1_units': 64, 'dropout_rate': 0.3}. Best is trial 0 with value: 0.47747299782397806.


  Results for fold 3:
    Accuracy: 0.6547085201793722
    Precision: 0.3273542600896861
    Recall: 0.5
    F1 Score: 0.3956639566395664
Average results across all folds:
  Accuracy: 0.6564407125396682
  Precision: 0.4348074216650208
  Recall: 0.5486587846427663
  F1 Score: 0.47747299782397806
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [13:17<00:00, 39.86s/it]


  Results for fold 1:
    Accuracy: 0.6442953020134228
    Precision: 0.6140790128921596
    Recall: 0.587369692346809
    F1 Score: 0.5841471192271911
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [13:10<00:00, 39.52s/it]


  Results for fold 2:
    Accuracy: 0.6502242152466368
    Precision: 0.6143105158730159
    Recall: 0.5996583636049126
    F1 Score: 0.6014663764463283
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [13:16<00:00, 39.85s/it]
[I 2024-06-04 01:34:54,480] Trial 1 finished with value: 0.5851593978755956 and parameters: {'conv1_filters': 48, 'conv2_filters': 128, 'conv3_filters': 256, 'fc1_units': 64, 'dropout_rate': 0.3}. Best is trial 1 with value: 0.5851593978755956.


  Results for fold 3:
    Accuracy: 0.6165919282511211
    Precision: 0.5711879940428457
    Recall: 0.5690935776552215
    F1 Score: 0.5698646979532674
Average results across all folds:
  Accuracy: 0.6370371485037268
  Precision: 0.5998591742693404
  Recall: 0.5853738778689811
  F1 Score: 0.5851593978755956
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [04:56<00:00, 14.83s/it]


  Results for fold 1:
    Accuracy: 0.6577181208053692
    Precision: 0.7147213855421687
    Recall: 0.5604182557843885
    F1 Score: 0.5124435921381877
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [04:55<00:00, 14.79s/it]


  Results for fold 2:
    Accuracy: 0.6569506726457399
    Precision: 0.6393377059670453
    Recall: 0.5564997405293202
    F1 Score: 0.5251059565317243
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [05:00<00:00, 15.01s/it]
[I 2024-06-04 01:49:55,489] Trial 2 finished with value: 0.5311829884365433 and parameters: {'conv1_filters': 16, 'conv2_filters': 96, 'conv3_filters': 64, 'fc1_units': 192, 'dropout_rate': 0.7}. Best is trial 1 with value: 0.5851593978755956.


  Results for fold 3:
    Accuracy: 0.647982062780269
    Precision: 0.5861108488339156
    Recall: 0.5608432663227184
    F1 Score: 0.555999416639718
Average results across all folds:
  Accuracy: 0.654216952077126
  Precision: 0.6467233134477098
  Recall: 0.5592537542121424
  F1 Score: 0.5311829884365433
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [11:54<00:00, 35.75s/it]


  Results for fold 1:
    Accuracy: 0.668903803131991
    Precision: 0.6488484985324001
    Recall: 0.6117467581998475
    F1 Score: 0.6105721685895926
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [11:48<00:00, 35.42s/it]


  Results for fold 2:
    Accuracy: 0.6434977578475336
    Precision: 0.599550763701707
    Recall: 0.5598944819235426
    F1 Score: 0.5456182280687141
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [11:39<00:00, 34.99s/it]
/home/erkkit/nnw/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
[I 2024-06-04 02:25:38,763] Trial 3 finished with value: 0.5172847844326244 and parameters: {'conv1_filters': 48, 'conv2_filters': 128, 'conv3_filters': 192, 'fc1_units': 64, 'dropout_rate': 0.6000000000000001}. Best is trial 1 with value: 0.5851593978755956.


  Results for fold 3:
    Accuracy: 0.6547085201793722
    Precision: 0.3273542600896861
    Recall: 0.5
    F1 Score: 0.3956639566395664
Average results across all folds:
  Accuracy: 0.655703360386299
  Precision: 0.5252511741079311
  Recall: 0.5572137467077968
  F1 Score: 0.5172847844326244
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [13:34<00:00, 40.70s/it]


  Results for fold 1:
    Accuracy: 0.6353467561521253
    Precision: 0.6048340548340548
    Recall: 0.5923595219933893
    F1 Score: 0.5931212410581159
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [13:12<00:00, 39.62s/it]


  Results for fold 2:
    Accuracy: 0.647982062780269
    Precision: 0.6083088954056696
    Recall: 0.5838522746929597
    F1 Score: 0.5821752283888368
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [13:32<00:00, 40.62s/it]
[I 2024-06-04 03:06:18,280] Trial 4 finished with value: 0.5975698740959969 and parameters: {'conv1_filters': 48, 'conv2_filters': 128, 'conv3_filters': 192, 'fc1_units': 256, 'dropout_rate': 0.3}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6524663677130045
    Precision: 0.6169197540387454
    Recall: 0.6179727806440135
    F1 Score: 0.617413152841038
Average results across all folds:
  Accuracy: 0.6452650622151329
  Precision: 0.6100209014261566
  Recall: 0.5980615257767875
  F1 Score: 0.5975698740959969
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [10:37<00:00, 31.89s/it]


  Results for fold 1:
    Accuracy: 0.6554809843400448
    Precision: 0.6286822491507378
    Recall: 0.6075514874141876
    F1 Score: 0.6083943931188276
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [10:39<00:00, 31.98s/it]


  Results for fold 2:
    Accuracy: 0.6771300448430493
    Precision: 0.6493103055175559
    Recall: 0.6132805742951046
    F1 Score: 0.6143073338297821
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [10:46<00:00, 32.31s/it]
[I 2024-06-04 03:38:39,289] Trial 5 finished with value: 0.595002063966283 and parameters: {'conv1_filters': 48, 'conv2_filters': 96, 'conv3_filters': 192, 'fc1_units': 128, 'dropout_rate': 0.7}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6659192825112108
    Precision: 0.6130278526504942
    Recall: 0.5699386230208148
    F1 Score: 0.5623044649502394
Average results across all folds:
  Accuracy: 0.6661767705647683
  Precision: 0.6303401357729294
  Recall: 0.5969235615767023
  F1 Score: 0.595002063966283
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [13:36<00:00, 40.83s/it]


  Results for fold 1:
    Accuracy: 0.6554809843400448
    Precision: 0.6506421457277651
    Recall: 0.5730676328502415
    F1 Score: 0.5492535358826611
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [13:39<00:00, 40.96s/it]


  Results for fold 2:
    Accuracy: 0.625560538116592
    Precision: 0.5862139373994091
    Recall: 0.5776033558207923
    F1 Score: 0.5785190844014374
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [13:50<00:00, 41.52s/it]
[I 2024-06-04 04:20:05,587] Trial 6 finished with value: 0.5698394968735243 and parameters: {'conv1_filters': 32, 'conv2_filters': 128, 'conv3_filters': 256, 'fc1_units': 256, 'dropout_rate': 0.7}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6278026905829597
    Precision: 0.5834713024282561
    Recall: 0.5807240704500979
    F1 Score: 0.5817458703364744
Average results across all folds:
  Accuracy: 0.6362814043465321
  Precision: 0.6067757951851435
  Recall: 0.5771316863737105
  F1 Score: 0.5698394968735243
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [05:22<00:00, 16.12s/it]


  Results for fold 1:
    Accuracy: 0.668903803131991
    Precision: 0.6461149961149961
    Recall: 0.6195334350368675
    F1 Score: 0.6209433443344334
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [05:38<00:00, 16.91s/it]
/home/erkkit/nnw/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


  Results for fold 2:
    Accuracy: 0.6322869955156951
    Precision: 0.31614349775784756
    Recall: 0.5
    F1 Score: 0.3873626373626374
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [05:43<00:00, 17.20s/it]
[I 2024-06-04 04:36:57,760] Trial 7 finished with value: 0.5456021187429686 and parameters: {'conv1_filters': 16, 'conv2_filters': 32, 'conv3_filters': 256, 'fc1_units': 128, 'dropout_rate': 0.7}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6883408071748879
    Precision: 0.6480507055728295
    Recall: 0.6238880982031667
    F1 Score: 0.6285003745318352
Average results across all folds:
  Accuracy: 0.663177201940858
  Precision: 0.5367697331485578
  Recall: 0.5811405110800114
  F1 Score: 0.5456021187429686
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [08:13<00:00, 24.67s/it]


  Results for fold 1:
    Accuracy: 0.610738255033557
    Precision: 0.5845024540676714
    Recall: 0.5824434274091025
    F1 Score: 0.5831475367662822
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [08:12<00:00, 24.63s/it]


  Results for fold 2:
    Accuracy: 0.600896860986547
    Precision: 0.5654090583601862
    Recall: 0.5632027330911606
    F1 Score: 0.5638405414908579
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [08:08<00:00, 24.42s/it]
[I 2024-06-04 05:01:44,048] Trial 8 finished with value: 0.5624139802619614 and parameters: {'conv1_filters': 16, 'conv2_filters': 96, 'conv3_filters': 192, 'fc1_units': 192, 'dropout_rate': 0.3}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6210762331838565
    Precision: 0.5544616673648931
    Recall: 0.5433641700764988
    F1 Score: 0.5402538625287441
Average results across all folds:
  Accuracy: 0.6109037830679869
  Precision: 0.5681243932642502
  Recall: 0.5630034435255873
  F1 Score: 0.5624139802619614
Fold 1:
  X_train shape: (892, 256, 256)
  y_train shape: (892,)
  X_val shape: (447, 256, 256)
  y_val shape: (447,)


Training fold 1: 100%|██████████| 20/20 [09:22<00:00, 28.15s/it]


  Results for fold 1:
    Accuracy: 0.5637583892617449
    Precision: 0.5640214606021781
    Recall: 0.5677599796592931
    F1 Score: 0.5577737753988992
Fold 2:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 2: 100%|██████████| 20/20 [09:26<00:00, 28.35s/it]


  Results for fold 2:
    Accuracy: 0.6457399103139013
    Precision: 0.6218596163639449
    Recall: 0.6241783428472583
    F1 Score: 0.6227946214457005
Fold 3:
  X_train shape: (893, 256, 256)
  y_train shape: (893,)
  X_val shape: (446, 256, 256)
  y_val shape: (446,)


Training fold 3: 100%|██████████| 20/20 [09:29<00:00, 28.49s/it]
[I 2024-06-04 05:30:19,491] Trial 9 finished with value: 0.5696913408193771 and parameters: {'conv1_filters': 32, 'conv2_filters': 96, 'conv3_filters': 256, 'fc1_units': 64, 'dropout_rate': 0.4}. Best is trial 4 with value: 0.5975698740959969.


  Results for fold 3:
    Accuracy: 0.6233183856502242
    Precision: 0.5495271432080571
    Recall: 0.5358699519658424
    F1 Score: 0.5285056256135316
Average results across all folds:
  Accuracy: 0.6109388950752902
  Precision: 0.5784694067247267
  Recall: 0.5759360914907979
  F1 Score: 0.5696913408193771
Best trial: [0.5975698740959969]
Best hyperparameters: {'conv1_filters': 48, 'conv2_filters': 128, 'conv3_filters': 192, 'fc1_units': 256, 'dropout_rate': 0.3}


: 

In [8]:
# BLOCK 8

# best_hyperparameters = best_trial.params
# best_model, results = train_and_evaluate(X_train_full, y_train_full, fold_count=7, **best_hyperparameters)
# def train_and_evaluate(X, y, fold_count=7, conv1_filters=32, conv2_filters=64, conv3_filters=128, fc1_units=128, dropout_rate=0.5):
best_model, results = train_and_evaluate(X_train_full, y_train_full, fold_count=7, conv1_filters=48, conv2_filters=64, conv3_filters=128, fc1_units=128, dropout_rate=0.3)
# best_model, results = train_and_evaluate(X_train_sample, y_train_sample, fold_count=7, conv1_filters=48, conv2_filters=64, conv3_filters=128, fc1_units=128, dropout_rate=0.3)


avg_results = np.mean(results, axis=0)
print("Final training with best hyperparameters:")
print(f"  Accuracy: {avg_results[0]}")
print(f"  Precision: {avg_results[1]}")
print(f"  Recall: {avg_results[2]}")
print(f"  F1 Score: {avg_results[3]}")

now = datetime.now()
timestamp = now.strftime("%Y%m%d_%H%M%S")
filename = f"best_simple_images_cnn_model_{timestamp}.pth"
print(f"Model will be saved as: {filename}")

if best_model is not None:
    torch.save(best_model, filename)
    print(f"Best model saved to '{filename}'.")

Training with 7 folds
Starting new fold


: 

In [8]:
# BLOCK 9 - Testing the model on the test set

def evaluate_model_on_test_set(model, X_test, y_test):
    model.eval()
    with torch.no_grad():
        test_predictions = []
        test_true = []
        for inputs, labels in DataLoader(TensorDataset(X_test, y_test), batch_size=16, shuffle=False):
            outputs = model(inputs)
            _, predicted = torch.max(outputs.data, 1)
            test_predictions.extend(predicted.numpy())
            test_true.extend(labels.numpy())

    accuracy = accuracy_score(test_true, test_predictions)
    precision = precision_score(test_true, test_predictions, average='macro')
    recall = recall_score(test_true, test_predictions, average='macro')
    f1 = f1_score(test_true, test_predictions, average='macro')

    print("Test set evaluation results:")
    print(f"  Accuracy: {accuracy}")
    print(f"  Precision: {precision}")
    print(f"  Recall: {recall}")
    print(f"  F1 Score: {f1}")

    return accuracy, precision, recall, f1

# Prepare the test data
X_test_tensor = torch.tensor(X_test_full, dtype=torch.float32).permute(0, 2, 1).unsqueeze(3)
y_test_tensor = torch.tensor(y_test_full, dtype=torch.long)

# Load the best model
model = CNNModel(**best_hyperparameters)
model.load_state_dict(torch.load(filename))

# Evaluate the model on the test set
evaluate_model_on_test_set(model, X_test_tensor, y_test_tensor)


Test set evaluation results:
  Accuracy: 0.917797717571217
  Precision: 0.9134568367293017
  Recall: 0.9055249910166071
  F1 Score: 0.9092475604292138


(0.917797717571217, 0.9134568367293017, 0.9055249910166071, 0.9092475604292138)